# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 357)
        MainWindow.setMaximumSize(QtCore.QSize(580, 357))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/root/img/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("border: none;\n"
"margin: 0 px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(43, 39, 38);\n"
"border: none;")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(8, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(40, 0))
        self.widget.setMaximumSize(QtCore.QSize(40, 16777215))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setStyleSheet("margin-bottom: 6px;\n"
"li")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/root/img/icon.ico"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_4.setStyleSheet("background-color: rgba(186, 204, 164, 0.4);\n"
"border-radius: 10px;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.btn_cronometro = QtWidgets.QPushButton(self.widget)
        self.btn_cronometro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cronometro.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"width: 40px;\n"
"height: 30px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_cronometro.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/root/img/cronometro.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cronometro.setIcon(icon1)
        self.btn_cronometro.setIconSize(QtCore.QSize(25, 25))
        self.btn_cronometro.setCheckable(True)
        self.btn_cronometro.setAutoExclusive(True)
        self.btn_cronometro.setObjectName("btn_cronometro")
        self.verticalLayout.addWidget(self.btn_cronometro)
        self.btn_pomodoro = QtWidgets.QPushButton(self.widget)
        self.btn_pomodoro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pomodoro.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"width: 40px;\n"
"height: 30px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_pomodoro.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/root/img/pomodoro.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pomodoro.setIcon(icon2)
        self.btn_pomodoro.setIconSize(QtCore.QSize(25, 25))
        self.btn_pomodoro.setObjectName("btn_pomodoro")
        self.verticalLayout.addWidget(self.btn_pomodoro)
        self.btn_regressivo = QtWidgets.QPushButton(self.widget)
        self.btn_regressivo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_regressivo.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"width: 40px;\n"
"height: 30px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_regressivo.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/root/img/30-segundos-em-um-cronometro.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_regressivo.setIcon(icon3)
        self.btn_regressivo.setIconSize(QtCore.QSize(25, 25))
        self.btn_regressivo.setObjectName("btn_regressivo")
        self.verticalLayout.addWidget(self.btn_regressivo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_info = QtWidgets.QPushButton(self.widget)
        self.btn_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_info.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"width: 40px;\n"
"height: 30px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_info.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/root/img/info.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_info.setIcon(icon4)
        self.btn_info.setObjectName("btn_info")
        self.verticalLayout.addWidget(self.btn_info)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("background-color: rgb(125, 173, 147);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget.setStyleSheet("background-color: rgb(43, 39, 38);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(186, 204, 164);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.line = QtWidgets.QFrame(self.page)
        self.line.setStyleSheet("background-color: rgb(186, 204, 164);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.lb_st_contador = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(72)
        self.lb_st_contador.setFont(font)
        self.lb_st_contador.setStyleSheet("color: rgb(1, 135, 144);\n"
"margin-top: 40px;\n"
"margin-bottom: 40px;")
        self.lb_st_contador.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_st_contador.setObjectName("lb_st_contador")
        self.verticalLayout_3.addWidget(self.lb_st_contador)
        self.widget_4 = QtWidgets.QWidget(self.page)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_st_reset = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(14)
        self.btn_st_reset.setFont(font)
        self.btn_st_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_st_reset.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_st_reset.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/root/img/restart.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_st_reset.setIcon(icon5)
        self.btn_st_reset.setIconSize(QtCore.QSize(30, 30))
        self.btn_st_reset.setObjectName("btn_st_reset")
        self.horizontalLayout_3.addWidget(self.btn_st_reset)
        self.btn_st_start = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(14)
        self.btn_st_start.setFont(font)
        self.btn_st_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_st_start.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_st_start.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/root/img/play-button-arrowhead.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_st_start.setIcon(icon6)
        self.btn_st_start.setIconSize(QtCore.QSize(30, 30))
        self.btn_st_start.setObjectName("btn_st_start")
        self.horizontalLayout_3.addWidget(self.btn_st_start)
        self.btn_st_stop = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(14)
        self.btn_st_stop.setFont(font)
        self.btn_st_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_st_stop.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_st_stop.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/root/img/pause.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_st_stop.setIcon(icon7)
        self.btn_st_stop.setIconSize(QtCore.QSize(35, 35))
        self.btn_st_stop.setObjectName("btn_st_stop")
        self.horizontalLayout_3.addWidget(self.btn_st_stop)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.stackedWidget.addWidget(self.page)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_14 = QtWidgets.QWidget(self.page_5)
        self.widget_14.setObjectName("widget_14")
        self.label_15 = QtWidgets.QLabel(self.widget_14)
        self.label_15.setGeometry(QtCore.QRect(50, 0, 371, 141))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/root/img/banner.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.page_5)
        self.widget_15.setObjectName("widget_15")
        self.label_16 = QtWidgets.QLabel(self.widget_15)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 491, 91))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setScaledContents(False)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.widget_15)
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.page_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(186, 204, 164);\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.line_2 = QtWidgets.QFrame(self.widget_3)
        self.line_2.setStyleSheet("background-color: rgb(186, 204, 164);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget_6 = QtWidgets.QWidget(self.page_2)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_pm_p1 = QtWidgets.QPushButton(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(12)
        self.btn_pm_p1.setFont(font)
        self.btn_pm_p1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pm_p1.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"width: 40px;\n"
"border-radius: 10px;\n"
"border:1px solid #bacca4;\n"
"color: #bacca4;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #bacca4;\n"
"border-radius: 10px;\n"
"    color: rgb(43, 39, 38);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_pm_p1.setObjectName("btn_pm_p1")
        self.horizontalLayout_5.addWidget(self.btn_pm_p1)
        self.btn_pm_p2 = QtWidgets.QPushButton(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(12)
        self.btn_pm_p2.setFont(font)
        self.btn_pm_p2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pm_p2.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"width: 40px;\n"
"border-radius: 10px;\n"
"border:1px solid #bacca4;\n"
"color: #bacca4;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #bacca4;\n"
"border-radius: 10px;\n"
"    color: rgb(43, 39, 38);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_pm_p2.setObjectName("btn_pm_p2")
        self.horizontalLayout_5.addWidget(self.btn_pm_p2)
        self.btn_pm_p3 = QtWidgets.QPushButton(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(12)
        self.btn_pm_p3.setFont(font)
        self.btn_pm_p3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pm_p3.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"width: 40px;\n"
"border-radius: 10px;\n"
"border:1px solid #bacca4;\n"
"color: #bacca4;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #bacca4;\n"
"border-radius: 10px;\n"
"    color: rgb(43, 39, 38);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_pm_p3.setObjectName("btn_pm_p3")
        self.horizontalLayout_5.addWidget(self.btn_pm_p3)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.lb_pm_contador = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(72)
        self.lb_pm_contador.setFont(font)
        self.lb_pm_contador.setStyleSheet("color: rgb(1, 135, 144);\n"
"padding-bottom: 4px;")
        self.lb_pm_contador.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_pm_contador.setObjectName("lb_pm_contador")
        self.verticalLayout_4.addWidget(self.lb_pm_contador)
        self.line_3 = QtWidgets.QFrame(self.page_2)
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.widget_5 = QtWidgets.QWidget(self.page_2)
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_pm_config = QtWidgets.QPushButton(self.widget_5)
        self.btn_pm_config.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_pm_config.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pm_config.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_pm_config.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/root/img/gear.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pm_config.setIcon(icon8)
        self.btn_pm_config.setIconSize(QtCore.QSize(30, 30))
        self.btn_pm_config.setObjectName("btn_pm_config")
        self.horizontalLayout_4.addWidget(self.btn_pm_config)
        self.btn_pm_start = QtWidgets.QPushButton(self.widget_5)
        self.btn_pm_start.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_pm_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pm_start.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_pm_start.setText("")
        self.btn_pm_start.setIcon(icon6)
        self.btn_pm_start.setIconSize(QtCore.QSize(30, 30))
        self.btn_pm_start.setObjectName("btn_pm_start")
        self.horizontalLayout_4.addWidget(self.btn_pm_start)
        self.pushButton = QtWidgets.QPushButton(self.widget_5)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.btn_pm_reset = QtWidgets.QPushButton(self.widget_5)
        self.btn_pm_reset.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_pm_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pm_reset.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_pm_reset.setText("")
        self.btn_pm_reset.setIcon(icon5)
        self.btn_pm_reset.setIconSize(QtCore.QSize(30, 30))
        self.btn_pm_reset.setObjectName("btn_pm_reset")
        self.horizontalLayout_4.addWidget(self.btn_pm_reset)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 34))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(24)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(186, 204, 164);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.line_6 = QtWidgets.QFrame(self.page_3)
        self.line_6.setStyleSheet("background-color: rgb(186, 204, 164);\n"
"")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_5.addWidget(self.line_6)
        self.widget_13 = QtWidgets.QWidget(self.page_3)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.spinBox_ct = QtWidgets.QSpinBox(self.widget_13)
        self.spinBox_ct.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.spinBox_ct.setFont(font)
        self.spinBox_ct.setStyleSheet("QSpinBox {\n"
"    color: lightgray;\n"
"    background: #2c2c2c;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
" ")
        self.spinBox_ct.setMaximum(5940)
        self.spinBox_ct.setObjectName("spinBox_ct")
        self.horizontalLayout_11.addWidget(self.spinBox_ct)
        self.btn_ct_save = QtWidgets.QPushButton(self.widget_13)
        self.btn_ct_save.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(12)
        self.btn_ct_save.setFont(font)
        self.btn_ct_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ct_save.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"width: 40px;\n"
"border-radius: 10px;\n"
"border:1px solid #bacca4;\n"
"color: #bacca4;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #bacca4;\n"
"border-radius: 10px;\n"
"    color: rgb(43, 39, 38);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_ct_save.setObjectName("btn_ct_save")
        self.horizontalLayout_11.addWidget(self.btn_ct_save)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.line_7 = QtWidgets.QFrame(self.widget_13)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_11.addWidget(self.line_7)
        self.verticalLayout_5.addWidget(self.widget_13)
        self.lb_ct_contador = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(72)
        self.lb_ct_contador.setFont(font)
        self.lb_ct_contador.setStyleSheet("color: rgb(1, 135, 144);\n"
"padding-bottom: 5px;")
        self.lb_ct_contador.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_ct_contador.setObjectName("lb_ct_contador")
        self.verticalLayout_5.addWidget(self.lb_ct_contador)
        self.widget_7 = QtWidgets.QWidget(self.page_3)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_ct_reset = QtWidgets.QPushButton(self.widget_7)
        self.btn_ct_reset.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_ct_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ct_reset.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_ct_reset.setText("")
        self.btn_ct_reset.setIcon(icon5)
        self.btn_ct_reset.setIconSize(QtCore.QSize(30, 30))
        self.btn_ct_reset.setObjectName("btn_ct_reset")
        self.horizontalLayout_6.addWidget(self.btn_ct_reset)
        self.btn_ct_start = QtWidgets.QPushButton(self.widget_7)
        self.btn_ct_start.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_ct_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ct_start.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_ct_start.setText("")
        self.btn_ct_start.setIcon(icon6)
        self.btn_ct_start.setIconSize(QtCore.QSize(30, 30))
        self.btn_ct_start.setObjectName("btn_ct_start")
        self.horizontalLayout_6.addWidget(self.btn_ct_start)
        self.btn_ct_stop = QtWidgets.QPushButton(self.widget_7)
        self.btn_ct_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ct_stop.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_ct_stop.setText("")
        self.btn_ct_stop.setIcon(icon7)
        self.btn_ct_stop.setIconSize(QtCore.QSize(35, 35))
        self.btn_ct_stop.setObjectName("btn_ct_stop")
        self.horizontalLayout_6.addWidget(self.btn_ct_stop)
        self.verticalLayout_5.addWidget(self.widget_7)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(186, 204, 164);")
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.line_5 = QtWidgets.QFrame(self.page_4)
        self.line_5.setStyleSheet("background-color: rgb(186, 204, 164);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_7.addWidget(self.line_5)
        self.widget_9 = QtWidgets.QWidget(self.page_4)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.widget_9)
        self.label_7.setMinimumSize(QtCore.QSize(110, 0))
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.spinBox_pm = QtWidgets.QSpinBox(self.widget_9)
        self.spinBox_pm.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.spinBox_pm.setFont(font)
        self.spinBox_pm.setStyleSheet("QSpinBox {\n"
"    color: lightgray;\n"
"    background: #2c2c2c;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
" ")
        self.spinBox_pm.setMaximum(5940)
        self.spinBox_pm.setProperty("value", 45)
        self.spinBox_pm.setObjectName("spinBox_pm")
        self.horizontalLayout_2.addWidget(self.spinBox_pm)
        self.label_8 = QtWidgets.QLabel(self.widget_9)
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.verticalLayout_7.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.page_4)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.widget_10)
        self.label_10.setMinimumSize(QtCore.QSize(110, 0))
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.spinBox_sb = QtWidgets.QSpinBox(self.widget_10)
        self.spinBox_sb.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.spinBox_sb.setFont(font)
        self.spinBox_sb.setStyleSheet("QSpinBox {\n"
"    color: lightgray;\n"
"    background: #2c2c2c;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
" ")
        self.spinBox_sb.setMaximum(5940)
        self.spinBox_sb.setProperty("value", 5)
        self.spinBox_sb.setObjectName("spinBox_sb")
        self.horizontalLayout_7.addWidget(self.spinBox_sb)
        self.label_9 = QtWidgets.QLabel(self.widget_10)
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.verticalLayout_7.addWidget(self.widget_10)
        self.widget_8 = QtWidgets.QWidget(self.page_4)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.widget_8)
        self.label_12.setMinimumSize(QtCore.QSize(110, 0))
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.spinBox_lb = QtWidgets.QSpinBox(self.widget_8)
        self.spinBox_lb.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.spinBox_lb.setFont(font)
        self.spinBox_lb.setStyleSheet("QSpinBox {\n"
"    color: lightgray;\n"
"    background: #2c2c2c;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
" ")
        self.spinBox_lb.setMaximum(5940)
        self.spinBox_lb.setProperty("value", 15)
        self.spinBox_lb.setObjectName("spinBox_lb")
        self.horizontalLayout_8.addWidget(self.spinBox_lb)
        self.label_11 = QtWidgets.QLabel(self.widget_8)
        self.label_11.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.verticalLayout_7.addWidget(self.widget_8)
        self.widget_12 = QtWidgets.QWidget(self.page_4)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.widget_12)
        self.label_13.setMinimumSize(QtCore.QSize(65, 0))
        self.label_13.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.checkBox_alert = QtWidgets.QCheckBox(self.widget_12)
        self.checkBox_alert.setMaximumSize(QtCore.QSize(40, 16777215))
        self.checkBox_alert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_alert.setStyleSheet("QCheckBox::indicator:unchecked {\n"
"    image: url(:/root/img/switch-off.ico);\n"
"    max-width:25px;\n"
"    max-height:25px;\n"
"    width: auto;\n"
"    height: auto;\n"
" }\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/root/img/switch-on.ico);\n"
"    max-width:25px;\n"
"    max-height:25px;\n"
"    width: auto;\n"
"    height: auto;\n"
"}")
        self.checkBox_alert.setText("")
        self.checkBox_alert.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_alert.setChecked(True)
        self.checkBox_alert.setObjectName("checkBox_alert")
        self.horizontalLayout_10.addWidget(self.checkBox_alert)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_2.setMinimumSize(QtCore.QSize(45, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(45, 50))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"margin: 0px;\n"
"border: none;\n"
"width: 40px;\n"
"height: 30px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #3b3b3b;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/root/img/bell.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon9)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        self.label_2 = QtWidgets.QLabel(self.widget_12)
        self.label_2.setMinimumSize(QtCore.QSize(125, 0))
        font = QtGui.QFont()
        font.setFamily("Alef")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.checkBox_autoplay = QtWidgets.QCheckBox(self.widget_12)
        self.checkBox_autoplay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_autoplay.setStyleSheet("QCheckBox::indicator:unchecked {\n"
"    image: url(:/root/img/switch-off.ico);\n"
"    max-width:25px;\n"
"    max-height:25px;\n"
"    width: auto;\n"
"    height: auto;\n"
" }\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/root/img/switch-on.ico);\n"
"    max-width:25px;\n"
"    max-height:25px;\n"
"    width: auto;\n"
"    height: auto;\n"
"}")
        self.checkBox_autoplay.setText("")
        self.checkBox_autoplay.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_autoplay.setChecked(False)
        self.checkBox_autoplay.setObjectName("checkBox_autoplay")
        self.horizontalLayout_10.addWidget(self.checkBox_autoplay)
        self.verticalLayout_7.addWidget(self.widget_12)
        self.widget_11 = QtWidgets.QWidget(self.page_4)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.btn_pm_salvar = QtWidgets.QPushButton(self.widget_11)
        self.btn_pm_salvar.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Abraham")
        font.setPointSize(12)
        self.btn_pm_salvar.setFont(font)
        self.btn_pm_salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pm_salvar.setStyleSheet("QPushButton {\n"
"padding: 5px;\n"
"width: 40px;\n"
"border-radius: 10px;\n"
"border:1px solid #bacca4;\n"
"color: #bacca4;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #bacca4;\n"
"border-radius: 10px;\n"
"    color: rgb(43, 39, 38);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #484848;\n"
"border-radius: 10px;\n"
"}")
        self.btn_pm_salvar.setObjectName("btn_pm_salvar")
        self.horizontalLayout_9.addWidget(self.btn_pm_salvar)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Snaketimer"))
        self.label_4.setText(_translate("MainWindow", "Stopwatch"))
        self.lb_st_contador.setText(_translate("MainWindow", "00:00:00"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Thanks so much for using Snaktimer! </p><p align=\"center\">Any problems, notify me on github.</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "POMODORO"))
        self.btn_pm_p1.setText(_translate("MainWindow", "POMODORO"))
        self.btn_pm_p2.setText(_translate("MainWindow", "SHORT BREAK"))
        self.btn_pm_p3.setText(_translate("MainWindow", "LONG BREAK"))
        self.lb_pm_contador.setText(_translate("MainWindow", "00:00:00"))
        self.label_14.setText(_translate("MainWindow", "countdown"))
        self.btn_ct_save.setText(_translate("MainWindow", "SALVAR"))
        self.lb_ct_contador.setText(_translate("MainWindow", "00:00:00"))
        self.label.setText(_translate("MainWindow", "POMODORO CONFIG"))
        self.label_7.setText(_translate("MainWindow", "POMODORO"))
        self.label_8.setText(_translate("MainWindow", " minutes."))
        self.label_10.setText(_translate("MainWindow", "short break"))
        self.label_9.setText(_translate("MainWindow", " minutes."))
        self.label_12.setText(_translate("MainWindow", "long break"))
        self.label_11.setText(_translate("MainWindow", " minutes."))
        self.label_13.setText(_translate("MainWindow", "ALERT "))
        self.label_2.setText(_translate("MainWindow", "beep.mp3"))
        self.label_3.setText(_translate("MainWindow", "AUTOPLAY"))
        self.btn_pm_salvar.setText(_translate("MainWindow", "Salvar"))
import assets.resource_rc
